.\" 
.TH "dr14_tmeter" "7" "0.8" "Simone Riva" "Sound"
.SH "NAME"
\fBdr14_tmeter\fR \- compute the DR14 value of the audio files according to the algorithm described
by the Pleasurize Music Foundation.
Visit: http://www.dynamicrange.de/ 

.SH "HOMEPAGE"
http://simon\-r.github.com/dr14_t.meter
.SH "DESCRIPTION"
\fBDR14 T.meter\fR is a free and opens source command line tool for computing the Dynamic Range of your music according to the procedure used in the off\-line meter released by the Pleasurize Music Foundation.

This tool is very useful to measure how is loud your music and for understanding that a good quality album always has also a good dynamic, and it's also useful for understanding the effects of the so called loudness war.


\fBOptions:\fR
  \fB\-\-version\fR             show program's version number and exit

  \fB\-h, \-\-help\fR            show this help message and exit

  \fB\-m, \-\-multithread\fR     Start the multithread mode

  \fB\-f, \-\-file\fR            Compute the DR14 of a single file

  \fB\-r, \-\-recursive\fR       Scan recursively the subdirectories

  \fB\-b, \-\-basic_table\fR      Write the resulting table in the basic format

  \fB\-o OUT_DIR, \-\-outdir=OUT_DIR\fR
                        Write the result files into the given directory

  \fB\-t OUT_TABLES, \-\-tables=OUT_TABLES\fR
                        Select the output files to be written, codes: h=html t=text b=bbcode
.SH "AUTHOR"
Written by Simone Riva.
.SH "REPORTING BUGS"
Report dr14_tmeter bugs to: https://github.com/simon\-r/dr14_t.meter/issues
.SH "COPYRIGHT"
Copyright (c) Simone Riva  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
