.\" 
.TH "dr14_tmeter" "1" "1.0.10" "Simone Riva" "Sound"
.SH "NAME"
\fBdr14_tmeter\fR \- compute the DR14 value of the audio files according to the algorithm described
by the Pleasurize Music Foundation.
Visit: http://www.dynamicrange.de/ 

.SH "HOMEPAGE"
http://dr14tmeter.scienceontheweb.net
.SH "DESCRIPTION"
\fBDR14 T.meter\fR is a free and opens source command line tool for computing the Dynamic Range of your music according to the procedure used in the off\-line meter released by the Pleasurize Music Foundation.

This tool is very useful to measure how is loud your music and for understanding that a good quality album always has also a good dynamic, and it's also useful for understanding the effects of the so called loudness war.

\fBusage\fR: dr14_tmeter [\-h] [\-v] [\-1] [\-r] [\-a] [\-b] [\-n] [\-p] [\-o OUT_DIR]
                   [\-t {h,t,b,w,a}] [\-f] [\-d] [\-\-hist] [\-\-lev_hist]
                   [\-\-spectrogram] [\-\-plot_track] [\-\-plot_track_dst]
                   [\-\-compress {very_soft,v,soft,s,medium,m,hard,h,very_hard,vh}]
                   [\-\-dyn_vivacity] [\-\-files_list] [\-\-quiet]
                   [path_name]



\fBpositional arguments:\fR
  path_name

\fBoptional arguments:\fR
\fB  \-h, \-\-help\fR            show this help message and exit

\fB  \-v, \-\-version\fR         show program's version number and exit

\fB  \-1, \-\-disable_multithread\fR
                        Disable the multi\-Core mode

\fB  \-r, \-\-recursive\fR       Scan recursively the subdirectories

\fB  \-a, \-\-append \fR         Append all results in a single file; it should be used
                        in couple with \-r

\fB  \-b, \-\-basic_table\fR     Write the resulting tables in the basic format

\fB  \-n, \-\-turn_off_out\fR    do not writes the output files

\fB  \-p, \-\-print_std_out\fR   writes the full result on the std_out

\fB  \-o OUT_DIR, \-\-outdir OUT_DIR\fR
                        Write the resultings files into the given directory

\fB  \-t {h,t,b,w,a}, \-\-tables {h,t,b,w,a}\fR
                        Select the output files to be written. h=html t=text
                        b=bbcode w=mediawiki a=all_formats

\fB  \-f, \-\-file\fR            Compute the DR14 of a single file and exit

\fB  \-d, \-\-dr_database\fR     Output file compatible with the DR database at
                        http:///www.dr.loudness\-war.info

\fB  \-\-hist\fR                Plot the histogram of dynamic of a single file and
                        exit

\fB  \-\-lev_hist\fR            Plot the histogram of the saples levels of a single
                        file and exit

\fB  \-\-spectrogram\fR         Plot the spectrogram of a single file and exit (beta)

\fB  \-\-plot_track\fR          Plot the track of the given file and exit                                                                                                                                                              
\fB  \-\-plot_track_dst\fR      Plot the track in a cool manner of the given file and exit 

\fB  \-\-compress {very_soft,v,soft,s,medium,m,hard,h,very_hard,vh}\fR
                        Perform the dynamic compression on a single file and
                        exit, the resulting track will be written in a temp
                        directory

\fB  \-\-dyn_vivacity\fR        Plot the graph of the dynamic vivacity of a single
                        audio file and exit

\fB  \-\-files_list\fR          takes a files list and compute the DR of each file, if
                        no files are specified, it reads from STDIN

\fB  \-\-quiet\fR               Quite mode





.SH "AUTHOR"
Written by Simone Riva.
.SH "REPORTING BUGS"
Report dr14_tmeter bugs to: https://github.com/simon\-r/dr14_t.meter/issues
.SH "COPYRIGHT"
Copyright (c) Simone Riva  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
